pipeline {
  agent {
    kubernetes {
      yaml """
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: jenkins-kaniko
spec:
  serviceAccountName: jenkins-sa
  containers:
    - name: kaniko
      image: gcr.io/kaniko-project/executor:v1.16.0-debug
      imagePullPolicy: Always
      command: ["sleep"]
      args: ["99d"]
    - name: git
      image: alpine/git
      command: ["cat"]
      tty: true
"""
    }
  }

  environment {
    AWS_REGION   = "us-west-2"
    ECR_REGISTRY = "065915236794.dkr.ecr.us-west-2.amazonaws.com"
    IMAGE_NAME   = "lesson-9-django-ecr"
    IMAGE_TAG    = "v1.0.${BUILD_NUMBER}"
    GIT_BRANCH   = "lesson-8-9"
    COMMIT_EMAIL = "jenkins@localhost"
    COMMIT_NAME  = "jenkins"
  }

  stages {
    stage('Build & Push Docker Image') {
      steps {
        container('kaniko') {
          withAWS(region: "${AWS_REGION}", credentials: 'aws-creds') {
            sh '''
              /kaniko/executor \
                --context `pwd`/lesson-8-9/django-docker-project \
                --dockerfile `pwd`/lesson-8-9/django-docker-project/Dockerfile \
                --destination=$ECR_REGISTRY/$IMAGE_NAME:$IMAGE_TAG \
                --cache=true
            '''
          }
        }
      }
    }

    stage('Update Chart Tag in Git') {
      steps {
        container('git') {
          withCredentials([usernamePassword(credentialsId: 'github-token', usernameVariable: 'GIT_USER', passwordVariable: 'GIT_PAT')]) {
            sh '''
              git clone --branch $GIT_BRANCH https://$GIT_USER:$GIT_PAT@github.com/LesiaUKR/my-microservice-project.git
              cd my-microservice-project/lesson-8-9/charts/django-app

              sed -i "s/tag: .*/tag: $IMAGE_TAG/" values.yaml

              git config user.email "$COMMIT_EMAIL"
              git config user.name "$COMMIT_NAME"

              git add values.yaml
              git commit -m "Update image tag to $IMAGE_TAG"
              git push origin HEAD
            '''
          }
        }
      }
    }
  }
}
